#!/bin/bash

# Licenced under the GNU GPL 3.0
# Part of AZOS GNU/Linux and all legal information from this legal page apply here: https://sites.google.com/view/azosofficialsite/legal

# basHelper, extremely lightweight, user-friendly and customizable AUR helper, that leaves almost non-existent trace behind on your system. "basH" because it is written in bash and "Helper"
# because it is an AUR helper.

# If you have a better name, open an issue or something XD

help(){
  printf ""
  printf "###################################################################################################################################################################" 
  printf "# Welcome to basHelper, the extremely lightweight and customizable AUR helper by Red Fire Software Entertainment for AZOS GNU/Linux and other Arch-Based distros. #"
  printf "###################################################################################################################################################################"
  printf ""
  printf "Syntax: bH [action] ([package])"
  printf ""
  printf "You can install up to 10 packages at once in this format:"
  printf "'bH -i/d [package] [package] [package] [package] [package] [package] [package] [package] [package] [package]'"
  printf ""
  printf "Actions:"
  printf "        -i | installs the specified package."
  printf "        -c | cleans up the terminal window so it can be nice and fresh, don't specify a package after."
  printf "        -d | installs the specified package and then clears the terminal window"
  printf "        -r | removes a package using pacman"
  printf "        -h | shows this, don't specify a package after"
  printf ""
  printf "Thank you for using bH! Many new features coming so stay tuned!"
  printf ""
}

clean(){
  printf "Clearing up..."
  sleep 3
  clear
}

install() {
    printf "Preparing to install $2"
    git clone https://aur.archlinux.org/cgit/aur.git/snapshot/$2.tar.gz/
    unzip $2.tar.gz ./
    cd ./$2
    makepkg --install --syncdeps --rmdeps --clean --noconfirm 
}

remove() {
    sudo pacman -R $2
}


if [ $1 == "-h" ] || [ $# -eq  1]
then
  help
else
  printf "Invalid Syntax."
fi

if [ $1 == "-c" ] || [ $# -eq  1]
then
  clean
else
  printf "Invalid Syntax."
fi

if [ $1 == "-d" ] || [ $# -eq  2]
then
  install
  clean
else
  printf "Invalid Syntax."
fi

if [ $1 == "-i" ] || [ $# -eq  2]
then
  install
else
  printf "Invalid Syntax."
fi

if [ $1 == "-r" ] || [ $# -eq  2]
then
  remove
else
  printf "Invalid Syntax."
fi
  
